version: '3.8'

services:
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI_AUTH=mongodb://auth-db:27017/auth
      - JWT_SECRET=secret-key
    depends_on:
      - auth-db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - VITE_AUTH_API_URL=http://backend:3001/auth
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth_data: